server:
  port: 8080
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: spring-demo-1
          uri: http://localhost:8081
          predicates:
            - Path=/hello1
        - id: spring-demo-2
          uri: http://localhost:8082
          predicates:
            - Path=/hello2