server:
  port: ${PORT:8080}
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: spring-demo-1
          uri: ${SPRING_DEMO_1_URL:http://localhost:8081}
          predicates:
            - Path=/hello1
        - id: spring-demo-2
          uri: ${SPRING_DEMO_2_URL:http://localhost:8082}
          predicates:
            - Path=/hello2